add manual approval

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,12 +6,23 @@ workflows:
       - integration-test:
           requires:
             - unit-test
-      #- deploy-heroku:
-      #    requires:
-      #      - build
-      - deploy:
+
+      #master only flow
+      - dark-deploy:
           requires:
             - integration-test
+          filters:
+            branches:
+              only: master
+      - hold:
+          type: approval
+          requires: dark-deploy
+          filters:
+            branches:
+              only: master
+      - live-deploy:
+          requires:
+            - hold
           filters:
             branches:
               only: master
@@ -132,7 +143,7 @@ jobs:
 #            fi
 #
 
-  deploy:
+  dark-deploy:
     docker:
       #- image: eddiewebb/queue-circleci-openjdk:8-jdk-browsers
       - image: circleci/openjdk:8-jdk
@@ -167,9 +178,41 @@ jobs:
               echo "dark route note available, failing deploy"
               exit 1
             fi
+
+
+  live-deploy:
+    docker:
+      #- image: eddiewebb/queue-circleci-openjdk:8-jdk-browsers
+      - image: circleci/openjdk:8-jdk
+    working_directory: ~/deploy
+    steps:
+      # why rebuild something we already tested, rebuilding invalidates any previous confidence?!
+      - attach_workspace:
+          at: /tmp
+
+      #- run: queueBuildUntilFrontOfLine 5 #do not run parallel deployments
+      - run:
+          name: Setup CF CLI
+          command: |
+            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
+            sudo dpkg -i cf-cli_amd64.deb
+            cf -v
+            cf api https://api.run.pivotal.io
+            cf auth $CF_USER $CF_PASSWORD
+            cf target -o eddies-org -s circleci
+
+      - run:
+          name: Re-route live Domain to latest
+          command: |
+            # Verify new version is working on dark URL.
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" http://dark.blueskygreenbuilds.com/`
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "dark route note available, failing deploy"
+              exit 1
+            fi
             # Send "real" url to new version
             cf map-route blueskygreenbuilds-dark www.blueskygreenbuilds.com
-            sleep 15 # give time to demo round robin
+            sleep 30 # give time to demo round robin
             # Stop sending traffic to previous version
             cf unmap-route blueskygreenbuilds www.blueskygreenbuilds.com
             # stop previous version
